services:
  jupyter:
    build: .
    container_name: my-jupyter
    user: "1000:1000"
    ports:
      - "8889:8888"
    volumes:
      - shared-data:/home/jovyan/app
    # environment:
    #   - JUPYTER_TOKEN=my-token
    networks:
      - gis-network

  db:
    image: postgis/postgis:16-3.4 
    container_name: my-postgis
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data # Standard path for postgres data
      - shared-data:/tmp
    env_file:
      - .env
    networks:
      - gis-network

networks:
  gis-network:

volumes:
  jupyter-data:
  pg-data:
  shared-data: #declared here, shared between containers
